export const knowledgeBasePageCopy = {
  createArticle: "New article",
  untitledArticleTitle: "Untitled article",
  createArticleDisabledLabel: "Select a group to create an article",
  placeholderEyebrow: "Main content placeholder",
  articlesEmptyTitle: "No articles found",
  articlesEmptyDescription:
    "This knowledge base group is empty right now. Add or move articles here when the content model expands.",
  searchPlaceholder: "Search articles...",
  groupPanelLabel: "Article groups",
  collapseGroupsLabel: "Collapse article groups",
  expandGroupsLabel: "Expand article groups",
  createGroupLabel: "Create group",
  createGroupNameLabel: "Group name",
  createGroupNamePlaceholder: "Group name",
  createGroupIconLabel: "Icon",
  createGroupSubmitLabel: "Add group",
  createGroupCancelLabel: "Cancel",
  createGroupEmptyNameLabel: "Enter a group name",
  pinArticleLabel: "Pin article",
  unpinArticleLabel: "Unpin article",
  archiveArticleLabel: "Archive article",
  groupArticlesLabel: "Articles",
  groupEmptyTitle: "No articles yet",
  groupEmptyDescription: "New articles can be added to this group later.",
  contentTab: "Content",
  insightsTab: "Insight",
  commentsTab: "Comment",
  activityTab: "Activity",
  articleCopyLinkLabel: "Copy link",
  articleLinkCopiedLabel: "Link copied",
  insightsCategoryLabel: "Category",
  statusPublished: "Published",
  statusDraft: "Draft",
  statusNeedsReview: "Needs review",
  articleToolbarAriaLabel: "Article formatting toolbar",
  articlePreviewLabel: "Preview",
  articleEditLabel: "Edit article",
  articleSaveLabel: "Save",
  articleCancelLabel: "Cancel",
  articleDiscardLabel: "Discard",
  articleNoChangesLabel: "No changes",
  articleUnsavedLabel: "Unsaved changes",
  articleChangeTitleLabel: "Title",
  articleChangeStatusLabel: "Status",
  articleChangeContentLabel: "Content",
  articleSingleChangeSuffix: "changed",
  articleMultipleChangesSuffix: "fields changed",
  articleDiscardTitle: "Discard unsaved changes?",
  articleDiscardDescription:
    "Your edits to this article will be lost if you leave without saving.",
  articleDiscardConfirmLabel: "Discard changes",
  articleLinkDialogTitle: "Add link",
  articleLinkDialogDescription: "Enter a URL for the selected text.",
  articleLinkDialogPlaceholder: "https://example.com",
  articleLinkDialogSaveLabel: "Apply link",
  articleLinkDialogRemoveLabel: "Remove link",
  articleLinkInvalidUrlLabel: "Enter a valid URL.",
  articleTitlePlaceholder: "Article title",
  articleStatusLabel: "Status",
  articleSaveSuccessLabel: "Article saved",
  articleToolbarBoldLabel: "Bold",
  articleToolbarItalicLabel: "Italic",
  articleToolbarUnderlineLabel: "Underline",
  articleToolbarCodeLabel: "Inline code",
  articleToolbarClearFormatLabel: "Clear formatting",
  articleToolbarParagraphLabel: "Paragraph",
  articleToolbarHeadingMenuLabel: "Heading",
  articleToolbarHeadingTwoLabel: "Heading 2",
  articleToolbarHeadingThreeLabel: "Heading 3",
  articleToolbarHeadingFourLabel: "Heading 4",
  articleToolbarHeadingFiveLabel: "Heading 5",
  articleToolbarHeadingSixLabel: "Heading 6",
  articleToolbarBulletListLabel: "Bullet list",
  articleToolbarNumberedListLabel: "Numbered list",
  articleToolbarBlockquoteLabel: "Quick path",
  articleToolbarDividerLabel: "Divider",
  articleToolbarLinkLabel: "Link",
  articleLinkPromptLabel: "URL",
  articleUpdatedPrefix: "Updated",
  articleLastEditedPrefix: "Last edited",
  articleBylineSeparator: "·",
  commentsTabCountFallback: "0",
  commentsComposerPlaceholder: "Comment or type '/' for commands",
  commentsComposerSubmitLabel: "Comment",
  commentsEmptyTitle: "No comments yet",
  commentsEmptyDescription:
    "Start an editorial discussion when this article needs review, clarification, or follow-up.",
  bodyCustomerReplyTitle: "Suggested customer reply",
  insightsViewsLabel: "Views",
  insightsHelpfulRateLabel: "Helpful rate",
  insightsLinkedTicketsLabel: "Linked tickets",
  insightsMatchSignalsLabel: "Match signals",
  insightsEmptyTitle: "Insight modules coming next",
  insightsEmptyDescription:
    "This area can expand into article performance, deflection quality, and usage context after the detail view is locked in.",
  activityEmptyTitle: "No activity yet",
  activityEmptyDescription:
    "Publishing, review, and article edit events will appear here.",
}
