export const knowledgeBasePageCopy = {
  createArticle: "New article",
  untitledArticleTitle: "Untitled article",
  createArticleDisabledLabel: "Select a group to create an article",
  placeholderEyebrow: "Main content placeholder",
  articlesEmptyTitle: "No articles found",
  articlesEmptyDescription:
    "This knowledge base group is empty right now. Add or move articles here when the content model expands.",
  searchPlaceholder: "Search articles...",
  groupPanelLabel: "Article groups",
  collapseGroupsLabel: "Collapse article groups",
  expandGroupsLabel: "Expand article groups",
  createGroupLabel: "Create group",
  createGroupNameLabel: "Group name",
  createGroupNamePlaceholder: "Group name",
  createGroupIconLabel: "Icon",
  createGroupSubmitLabel: "Add group",
  createGroupCancelLabel: "Cancel",
  createGroupEmptyNameLabel: "Enter a group name",
  groupArticlesLabel: "Articles",
  groupEmptyTitle: "No articles yet",
  groupEmptyDescription: "New articles can be added to this group later.",
  contentTab: "Content",
  insightsTab: "Insight",
  commentsTab: "Comment",
  activityTab: "Activity",
  articleCopyLinkLabel: "Copy link",
  articleLinkCopiedLabel: "Link copied",
  insightsCategoryLabel: "Category",
  statusPublished: "Published",
  statusDraft: "Draft",
  statusNeedsReview: "Needs review",
  articleToolbarAriaLabel: "Article formatting toolbar",
  articlePreviewLabel: "Preview",
  articleEditLabel: "Edit article",
  articleSaveLabel: "Save",
  articleCancelLabel: "Cancel",
  articleNoChangesLabel: "No changes",
  articleUnsavedLabel: "Unsaved changes",
  articleDiscardTitle: "Discard unsaved changes?",
  articleDiscardDescription:
    "Your edits to this article will be lost if you leave without saving.",
  articleDiscardConfirmLabel: "Discard changes",
  articleLinkDialogTitle: "Add link",
  articleLinkDialogDescription: "Enter a URL for the selected text.",
  articleLinkDialogPlaceholder: "https://example.com",
  articleLinkDialogSaveLabel: "Apply link",
  articleLinkDialogRemoveLabel: "Remove link",
  articleLinkInvalidUrlLabel: "Enter a valid URL.",
  articleTitlePlaceholder: "Article title",
  articleStatusLabel: "Status",
  articleSaveSuccessLabel: "Article saved",
  articleToolbarBoldLabel: "Bold",
  articleToolbarItalicLabel: "Italic",
  articleToolbarUnderlineLabel: "Underline",
  articleToolbarHeadingTwoLabel: "Heading 2",
  articleToolbarHeadingThreeLabel: "Heading 3",
  articleToolbarBulletListLabel: "Bullet list",
  articleToolbarNumberedListLabel: "Numbered list",
  articleToolbarLinkLabel: "Link",
  articleLinkPromptLabel: "URL",
  articleUpdatedPrefix: "Updated",
  articleLastEditedPrefix: "Last edited",
  articleBylineSeparator: "·",
  commentsTabCountFallback: "0",
  bodyQuickPathTitle: "Quick look",
  bodyCustomerReplyTitle: "Suggested customer reply",
  insightsViewsLabel: "Views",
  insightsHelpfulRateLabel: "Helpful rate",
  insightsLinkedTicketsLabel: "Linked tickets",
  insightsMatchSignalsLabel: "Match signals",
  insightsEmptyTitle: "Insight modules coming next",
  insightsEmptyDescription:
    "This area can expand into article performance, deflection quality, and usage context after the detail view is locked in.",
  commentsEmptyTitle: "Comments shell goes here",
  commentsEmptyDescription:
    "Inline review notes, editorial discussion, and content feedback can plug into this tab later.",
  activityEmptyTitle: "Activity shell goes here",
  activityEmptyDescription:
    "Version history, article changes, and related publishing events can be surfaced here next.",
}
